# Site settings
title: A random blog
description: "Some description here"
url: "http://www.jacoporabolini.com/emerald"
author:
  name: "Andrew Kharchyshyn"
  email: "haawaplus@gmail.com"
  url: "http://www.jacoporabolini.com"

# Build settings
baseurl: /emerald/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# Gems
gems: [jekyll-paginate]
